global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'kdhinesh2005@gmail.com'
  smtp_auth_username: 'kdhinesh2005@gmail.com'
  smtp_auth_password: 'wuqz ioed zhox afiq' # 16-digit Google App Password
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-receiver'

receivers:
  - name: 'email-receiver'
    email_configs:
      - to: 'kdhinesh2005@gmail.com'
        send_resolved: true